server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dilwit/spring-config-repo.git
          search-paths:
            - '{application}'
            

# Enbale HTTP Basic authentication for all end-points via spring-boot-security
security:
  basic: 
    enabled: true
  user: 
    name: xyz
    password: 123456