server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dilwit/spring-config-repo.git
          username: dilwit
          password: bad13f9efa22a45035eba113719600143b0e7694
          # Pulls git repo by force if local copy gets dirty
          force-pull: true
          search-paths:
            - '{application}/{profile}'
            

# Enbale HTTP Basic authentication for all end-points via spring-boot-security
security:
  basic:
    enabled: true
  user:
    name: xyz
    password: 123456